### PR TITLE
Add Github C2 channel 

### PR DESCRIPTION
**Pull request by sunnyneo**
Pull request for Github C2 channel. I reused codes from the Dropbox modules heavily because they have similar workflow and it helped me ease into the framework.

Let me know if you need anything else.

### CODE REVIEW

**Comment by invictus-0x90** [comment]
Awesome, there's nothing wrong at all with reusing code, it should be encouraged really. Thanks for the PR will be looked at when someone is available!

**Comment by purple-party** [comment]
Hey @sunnyneo, I get a 'Packet handling failure. Message forged' error on the gateway when I try and launch a GitHub negotiation channel. The non-negotiation channel works perfectly though. Have you seen anything like that before?

**Comment by ajpc500** [comment]
Hey @sunnyneo, I get a 'Packet handling failure. Message forged' error on the gateway when i try to launch a Github negotiation channel. The non-negotiation channel works perfectly though. Have you experienced anything like that before?

**Comment by sunnyneo** [comment]
Hi @ajpc500 , thanks for reviewing the pull request. 

I did not notice the error message during the initial testing of the negotiation channel. However I have just re-tested "add negotiation channel" several times and the same error message 'Packet handling failure. Message forged' only occurred at the first attempt when I started testing but not any more after that even with 10 additional attempts as you can see in the screenshot below. 

However, I did get intermittent ``Packet handling failure. Message forged`` during multiple attempts to launch a relay binary to connect to the negotiation channel and it seems to always happen after ``FSecure::GithubApi::DeleteFile`` function. I am looking into this, and will get back if I have any updates. As of now, it seems some what tricky because I can't reproduce the error reliably, do let me know if you have any ideas. 

image

**Comment by invictus-0x90** [comment]
Hey so there could be a few causes for this issue, the reason it is happening after DeleteFile is because after that call returns the packet is passed to C3's core code which does further checks. I've been able to reproduce the issues above, initially I thought it might be the file not being deleted properly or a race condition along those lines, but that doesn't seem to be the case. 

I am wondering however if there's an issue with the way github decodes/represents the raw binary. I've tested double encoding the content and the decoding in ReadFile and haven't had any issues yet. Example:

`j[OBF("content")] = cppcodec::base64_rfc4648::encode(cppcodec::base64_rfc4648::encode(data));`
....
`auto content = cppcodec::base64_rfc4648::decode(SendHttpRequest(url, OBF("application/vnd.github.v3.raw"), Method::GET, true));`

I Staged 6 relays in quick succession without any issues where previously I'd get the packet handling error after the first. Give it a test and let me know.

**Comment by ajpc500** [comment]
> Hey so there could be a few causes for this issue, the reason it is happening after DeleteFile is because after that call returns the packet is passed to C3's core code which does further checks. I've been able to reproduce the issues above, initially I thought it might be the file not being deleted properly or a race condition along those lines, but that doesn't seem to be the case.
> 
> I am wondering however if there's an issue with the way github decodes/represents the raw binary. I've tested double encoding the content and the decoding in ReadFile and haven't had any issues yet. Example:
> 
> `j[OBF("content")] = cppcodec::base64_rfc4648::encode(cppcodec::base64_rfc4648::encode(data));`
> ....
> `auto content = cppcodec::base64_rfc4648::decode(SendHttpRequest(url, OBF("application/vnd.github.v3.raw"), Method::GET, true));`
> 
> I Staged 6 relays in quick succession without any issues where previously I'd get the packet handling error after the first. Give it a test and let me know.

Yep, double-encoding worked for me 👍

**Comment by ajpc500** [comment]
Also, i'm not sure if that 150mb write size in Github.cpp is an artefact of the Dropbox channel, looking at the Github API, i think there's a 1mb limit on reading file contents. In which case, accounting for the base64 encoding our OnSendToChannel might need to be something like this? 

`size_t FSecure::C3::Interfaces::Channels::Github::OnSendToChannel(ByteView data)
{

	constexpr auto maxPacketSize = cppcodec::base64_rfc4648::decoded_max_size(1024 * 1024); // the max size is 1MB
	auto actualPacketSize = std::min(maxPacketSize, data.size());
	auto sendData = data.SubString(0, actualPacketSize);

	m_githubObj.WriteMessageToFile(m_outboundDirectionName, sendData);
	return actualPacketSize;
}`

**Comment by customc2** [comment]
Hi @invictus-0x90 

Thanks so much for your help. I went into the same route with race condition and implemented mutex and lock but it did not resolve the issue. Then I noticed that certain value from the Relay sent to Github seems to work and most don't, after launching the same Relay client multiple times. I agree with your hypothesis and have switched the affected codes to your suggestions. So far I have not encountered any error message even though I have tested numerous times.

On other note, I have added some fixes to delete the repository instead of the files for Delete All Files and also added 1 MB file limit updates. (@ajpc500)

Let me know if there is anything else.

**Comment by sunnyneo** [comment]
Hi @invictus-0x90

Thanks so much for your help. I went into the same route with race condition and implemented mutex and lock but it did not resolve the issue. Then I noticed that certain value from the Relay sent to Github seems to work and most don't, after launching the same Relay client multiple times. I agree with your hypothesis and have switched the affected codes to your suggestions. So far I have not encountered any error message even though I have tested numerous times.

In addition, I have added some fixes to delete the repository instead of the files for Delete All Files and also added 1 MB file limit updates after testing the channel using ChannelLinter. There's no issue with writing more than 1 MB except, reading the raw file does require to accessing the Blob instead (@ajpc500)

Let me know if there is anything else.

**Comment by pawelkurowski** [comment]
https://stackoverflow.com/questions/36519095/github-api-returns-wrong-file-content is causing the problem with wrong packet body. Base64 was making files plain text which was avoiding problem. You can use `raw.githubusercontent.com` in `ReadFile` function :
```
	std::string url = OBF("https://raw.githubusercontent.com/") + this->m_Username + OBF("/") + this->m_Channel
						+ OBF("/master/") + filename;

	ByteVector content = SendHttpRequest(url, "", Method::GET, true);
```

P.S. If you need to verify msg size, adding empty `Accept-Encoding` header to request, makes  `Content-Length` header of response equal to packet size, otherwise this header will show transmission gziped size.

**Comment by pawelkurowski** [comment]
Starting a lot of relays at the same time causes `409 Conflict` response on write to repository. I think it should be handled like `429 Too Many Requests`

**Comment by sunnyneo** [comment]
> https://stackoverflow.com/questions/36519095/github-api-returns-wrong-file-content is causing the problem with wrong packet body. Base64 was making files plain text which was avoiding problem. You can use `raw.githubusercontent.com` in `ReadFile` function :
> 
> ```
> 	std::string url = OBF("https://raw.githubusercontent.com/") + this->m_Username + OBF("/") + this->m_Channel
> 						+ OBF("/master/") + filename;
> 
> 	ByteVector content = SendHttpRequest(url, "", Method::GET, true);
> ```
> 
> P.S. If you need to verify msg size, adding empty `Accept-Encoding` header to request, makes `Content-Length` header of response equal to packet size, otherwise this header will show transmission gziped size.

Switched to raw.githubusercontent.com because it does not require double base64 encoding (save bandwidth), does not have any file size limitation for reading and this approach does not trigger Github API rate limiting.  

> Starting a lot of relays at the same time causes `409 Conflict` response on write to repository. I think it should be handled like `429 Too Many Requests`

Handled 409 Conflict like 429 Too Many Request.

Thanks for the feedback!

**Pull request merged**
